### PR TITLE
Added PuppetAvatar.cs Script

### PR DESCRIPTION
**Pull request by anantley**
Added script to apply joint rotations from Azure Kinect to any humanoid avatar in Unity.

The steps to apply are: 
1) go to the sample scene in the unity sample application
2) add an avatar and make it a humanoid in the inspector
3) apply the PuppetAvatar script to the avatar
4) set the public fields for the azure kinect tracker and the pelvis of the display figure
5) add an empty Animator Controller to your avatar
6) press play

Still to do:  
1) enable multi skeleton application of joints
2) handle scale for different sized avatars

### CODE REVIEW

**Comment by dotMorten** [comment]
Thanks for this @anantley. Any chance you have a script that also works with the RocketBox Avatars recently released? I tried and all I got was a contortionist and had a hard time figuring out the right values to apply.

RocketBox Avatars repo: https://github.com/microsoft/Microsoft-Rocketbox
Article: https://www.microsoft.com/en-us/research/blog/microsoft-rocketbox-avatar-library-now-available-for-research-and-academic-use/

**Comment by anantley** [comment]
Sure happy to take a look this week.

Angus

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by genereddick** [comment]
When I run with a random avatar, it applies the correct movements, but the avatar is rotated. I haven't been able to find where the rotation is coming from. 
image

**Comment by anantley** [comment]
This usually means there is an extra root node on the character.  Instead of root-> hips you have root->something else with a rotation about x-> hips

Angus

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by genereddick** [comment]
This is the asset structure: 

image

Does that mean that the Puppet Avatar script should be on the "root" gameObject in this model?

**Comment by dotMorten** [comment]
@anantley This might be helpful for the RocketBox Avatars to get each joint based on JointId. My problem was mainly with getting rotation and position right. The sample uses a flat hierarchy whereas Rocketbox is more "intricate":

```cs
	private Transform GetJoint(JointId id)
	{
		if(id == JointId.Pelvis)
		{
			return transform.Find("Bip01").Find("Bip01 Pelvis");
		}
		else if(id == JointId.SpineNavel)
		{
			return GetJoint(JointId.Pelvis).Find("Bip01 Spine");
		}
		else if(id == JointId.SpineChest)
		{
			return GetJoint(JointId.SpineNavel).Find("Bip01 Spine1").Find("Bip01 Spine2");
		}
		else if(id == JointId.Head)
		{
			return GetJoint(JointId.Neck).Find("Bip01 Head");
		}
		else if(id == JointId.Neck)
		{
			return GetJoint(JointId.SpineChest).Find("Bip01 Neck");
		}
		else if(id == JointId.ClavicleLeft)
		{
			return GetJoint(JointId.Neck).Find("Bip01 L Clavicle");
		}
		else if(id == JointId.ClavicleRight)
		{
			return GetJoint(JointId.Neck).Find("Bip01 R Clavicle");
		}		
		else if(id == JointId.ShoulderLeft)
		{
			return GetJoint(JointId.ClavicleLeft).Find("Bip01 L UpperArm");
		}
		else if(id == JointId.ShoulderRight)
		{
			return GetJoint(JointId.ClavicleRight).Find("Bip01 R UpperArm");
		}
		else if(id == JointId.ElbowLeft)
		{
			return GetJoint(JointId.ShoulderLeft).Find("Bip01 L Forearm");
		}
		else if(id == JointId.ElbowRight)
		{
			return GetJoint(JointId.ShoulderRight).Find("Bip01 R Forearm");
		}
		else if(id == JointId.WristLeft)
		{
			return GetJoint(JointId.ElbowLeft).Find("Bip01 L Hand");
		}
		else if(id == JointId.WristRight)
		{
			return GetJoint(JointId.ElbowRight).Find("Bip01 R Hand");
		}
		else if(id == JointId.HipLeft)
		{
			return GetJoint(JointId.SpineNavel).Find("Bip01 L Thigh");
		}
		else if(id == JointId.HipRight)
		{
			return GetJoint(JointId.SpineNavel).Find("Bip01 R Thigh");
		}
		else if(id == JointId.KneeLeft)
		{
			return GetJoint(JointId.HipLeft).Find("Bip01 L Calf");
		}
		else if(id == JointId.KneeRight)
		{
			return GetJoint(JointId.HipRight).Find("Bip01 R Calf");
		}		
		else if(id == JointId.AnkleLeft)
		{
			return GetJoint(JointId.KneeLeft).Find("Bip01 L Foot");
		}
		else if(id == JointId.AnkleRight)
		{
			return GetJoint(JointId.KneeRight).Find("Bip01 R Foot");
		}		
		else if(id == JointId.FootLeft)
		{
			return GetJoint(JointId.AnkleLeft).Find("Bip01 L Toe0");
		}
		else if(id == JointId.AnkleRight)
		{
			return GetJoint(JointId.FootRight).Find("Bip01 R Toe0");
		}
		return null;
	}
```

**Comment by anantley** [comment]
I’d have to see it myself to tell you what to do.  But it looks like what I was thinking there is probably a rotation on Female mannequin and then a counter rotation on “root”.

Can I have access to this avatar to take a look?

Angus

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by genereddick** [comment]
@anantley Here is the model
https://1drv.ms/u/s!Ahk_r7KQn8xsg6wcrPtcDL6MoyCVZw?e=V0J5iy

The first model has a -90 x rotation on the root and a 90 y rotation on the pelvis.

The second model has a -90 x rotation on the Bip01 (root) and a -90 x rotation on the Bio01 Pelvis.

Similar issues on another model. 
image

image

**Comment by genereddick** [comment]
Tested another rig that was Parent gameObject : Pelvis and that one worked, versus the ones that are Parent gameObject : root : pelvis, which did not.

**Comment by anantley** [comment]
Great thanks for the update, I should be able to fix this today

Angus

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by anantley** [comment]
@dotMorten 
The fix for RocketBox is the following
1) apply humanoid to the model
2) press configure
3) in the Hierarchy window select the Bip01 joint 
image
and zero out the eulers. This is tricky because in my editor they look like they are zero until you hover over the transform window.
image
Then select the Bip01 Pelvis joint and set the eulers to 0,-90,-90
image
Then hip apply and you should be set to go.  

Let me know if you have any problems with that

**Comment by anantley** [comment]
@genereddick @dotMorten  I made a new version of the puppetmaster.cs script that should handle all the cases with the extra root nodes above the pelvis.  It would be great if you could try them out on your problem avatars and let me know what happens.
https://gist.github.com/anantley/b584ddd75a038f36ca8d9c297a79670c

**Comment by genereddick** [comment]
@anantley I tested with three different avatars. The one that was working previously and the two with the parent:root:pelvis hierarchy. All three work with the correct rotations. Thanks!

Not a serious issue but there is an short period between when the project starts and the body tracking rotations are first applied where the two (previously non-working) models jump to their incorrect rotations before correcting.

**Comment by anantley** [comment]
Great thanks for testing.
Angus

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dotMorten** [comment]
Rocketbox!
Untitled Project

**Comment by dotMorten** [comment]
One thing I did have a problem with was that the character doesn't move around. Ie if I walk a step forward, the character doesn't move a step forward. On the upside, I can moonwalk now :)

**Comment by margonzalezfranco** [comment]
Hi @dotMorten did you solve that? I have the translations working too if you are interested

Mar

**Comment by dotMorten** [comment]
@margonzalezfrance nope I didn't. Would love to hear how you solved it.

**Comment by margonzalezfranco** [comment]
Hi, In the late update after updating all the joins of the avatar you have to translate the pelvis

 if (currentbone.name == RootPosition.name)
                            {
                                GameObject MoCapBone = GameObject.Find(GetKinectObjectName(currentbone.name));
                                Vector3 v = MoCapBone.transform.position;
                                finalJoint.localPosition = new Vector3(OffsetX - v.z, OffsetY - v.x, OffsetZ + v.y);
                            }

For everyone here, we will be releasing a new animator tool specific for rocketbox in unity
thanks

**Comment by ElliMary** [comment]
Thanks for all the working basics, examples and scripts!
For a research work I measured the latency for the Kinect and also in this Unity Code Example and unfortunately I got relatively high results (more than 500 ms). For the 3d viewer application of the kinect itself I already had latency values of over 140 ms.
Do others here also have very high latencies in this Unity Code Example? Or also around 140 ms within the 3D Viewer application?
I'm trying to find out what kind of adjustment screws increase the latency between the kinect 3D viewer application and the Unity bodytracking application.
Can anyone give an insight into how computationally intensive the body tracking calculations within the Unity project are?
Thanks a lot in advance!

**Comment by anantley** [comment]
Hi @ElliMary can you tell me what your gpu is?  That can make a big difference for latency.

**Comment by ElliMary** [comment]
Hi @anantley, my GPU is NVIDIA GeForce RTX 2070 SUPER.

**Comment by Vandor1** [comment]
@anantley 
> Still to do:
> 
> 1. enable multi skeleton application of joints
> 2. handle scale for different sized avatars

Any updates on this? I am currently working on a project where I have multiple skeletons - and I want to add separate avatars on top of them. Currently all my avatars are following the motion of one skeleton.

**Comment by asergaz** [comment]
Related with SO Thread: https://stackoverflow.com/questions/72040748/azure-kinect-dk-body-tracking-mapping-separate-avatars-on-separate-skeletons

**Pull request merged**
