### PR TITLE
Updated sample unity BT application

### PR DESCRIPTION
**Pull request by fkavache**

### CODE REVIEW

**Comment by amantley** [comment]
Hi @fkavache these changes look good to me!  I am going to clone a fresh repo and follow the README to see if there are any improvements we can make there.  After that I will approve.

**Comment by amantley** [comment]
@fkavache Hi Vache,  I went through the README this morning and was able to load everything using the .bat file so all good there.  However, I got  the startup error when pressing play in the editor in GPU mode.  I don't have cuda 11.4.3 installed, I couldn't tell if that was necessary from looking at the doc in the dependency matrix.  If it is necessary I think we should make sure we emphasize that in the README

**Comment by fkavache** [comment]
@amantley Thank you for the feedback!

Yes, additionally 
for **CUDA** you need to have **CUDA + cuDNN** installed
for **TRT** you need to have **CUDA  + TensorRT** installed
described in the 2nd step, maybe it's not clear, I agree with that.

Also for all of the EPs **Visual C++ Redistributable** is necessary which I haven't mentioned in readme.

Also all this is described in [BT SDK Setup Guide](https://docs.microsoft.com/en-us/azure/kinect-dk/body-sdk-setup)

So we can discuss what we want to mention in the readme.

**Comment by amantley** [comment]
Hi @fkavache 

Ok now I have TrackerProcessingMode.Cuda working but not DirectML or Gpu.   A couple of things are confusing. 
1) In the attached snippet it says that gpu mode defaults to cuda on windows. But I can't get gpu mode to start up, whereas cuda is working.
image
2) also in the readme it says to set a path variable for cuda and cudnn, It would be good to show what that path should look like. ie is it  something like C:\Program Files\NVIDIA GPU Computing Toolkit\cudnn-11.4-windows-x64-v8.2.2.26 ??

**Comment by amantley** [comment]
Hi @fkavache,  Great Job on getting this all working!!!  

Sorry I didn't see that path for where to put the directml file before.  Everything works that I tried.  I didn't have time to check the TRT.   The main points of confusion for me in following the README was what I needed to do to get the cuda and directml versions working.  Maybe we should just over-document that part, like saying:

1) install cuda version recommended.  
2) the path CUDA_PATH should already be added to enviroment variables looking something like this: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4
3) install cudnn version and put it  "NVidia GPU Computing Toolkit" directory under program files,
4) add a value to the path enviroment variable for it C:\Program Files\NVIDIA GPU Computing Toolkit\cudnn-11.4-windows-x64-v8.2.2.26 
5) take the directml.dll from the sampleunitybodytracking folder and copy it to the editor directory, typically something like this
C:\Program Files\Unity\Hub\Editor\2019.1.2f1\Editor
6) in the SkeletalTrackingProvider.cs script change the TrackingProvider to the one you want e.g. ProcessingMode = TrackerProcessingMode.DirectML or ProcessingMode = TrackerProcessingMode.Cuda

This is a frequently misunderstood setup so it would be a great service if we could make this a process that people can follow effectively.  The more example paths the better I think.

**Comment by fkavache** [comment]
Hi @amantley

I have updated README.md, please take a look for the final word.

Thanks!

**Review by amantley — APPROVED** [review]
README looks good!

**Review by anantley — APPROVED** [review]

**Pull request merged**
